Script started on 2017年03月11日 (週六) 00時28分43秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/school/download $[00m whoami;pwd
pd2vm
/home/pd2vm/school/download
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/school/download $[00m git config -l
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/school/download $[00m git clone http://github.com/HwanHs uanChang/lab.1.[Cgit
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/school/download $[00m 
Script done on 2017年03月11日 (週六) 00時31分37秒
